FROM alpine:latest

MAINTAINER Sotiris Pelekis

# Set the working directory
WORKDIR  /app

# Copy the current directory contents into the container at /app
# COPY  ./behaviour-attack-simulator-flask /app

# Install D-ITG and compile
RUN apk update && \
    #apk upgrade && \
    #apk add bash && \
    apk add wget && \
    apk add make && \
    apk add g++ && \
    apk add unzip && \
    apk add tcpdump && \
    wget http://traffic.comics.unina.it/software/ITG/codice/D-ITG-2.8.1-r1023-src.zip && \
    unzip D-ITG-2.8.1-r1023-src.zip && \
    mv D-ITG-2.8.1-r1023 D-ITG && \
    rm -r D-ITG-2.8.1-r1023-src.zip

WORKDIR /app/D-ITG/src

RUN make

RUN cp libITG/libITG.so /usr/local/lib

ENV LD_LIBRARY_PATH /usr/local/lib

WORKDIR /app/

#COPY ./sender-receiver.sh .

#RUN chmod 777 sender-receiver.sh

ENTRYPOINT ["ash"]
#CMD ["sender-receiver.sh"]

#ENTRYPOINT ["ash"]
#CMD D-ITG/bin/ITGRecv &> receiver.stdout && D-ITG/bin/ITGSend -Q -l sender.log -x receiver.log &>sender.stdout
