version: "3"
services:

  node1:
    #image:pelekhs/behaviour_node
    container_name: node1
    build:
      context: .
      dockerfile: Dockerfile-node
    networks:
      - sphinx-net
    working_dir: /app
    command: ["./sender-receiver.sh"]

  node2:
    #image:pelekhs/behaviour_node
    container_name: node2
    build:
      context: .
      dockerfile: Dockerfile-node
    networks:
      - sphinx-net
    working_dir: /app
    command: ["./sender-receiver.sh"]

  supervisor:
    #image:pelekhs/behaviour_supervisor
    container_name: super
    build:
      context: .
      dockerfile: Dockerfile-supervisor
    ports:
      - "5002:5002"
    networks:
      - sphinx-net


networks:
  sphinx-net:
    driver: bridge
