FROM kalilinux/kali-rolling:latest

MAINTAINER Sotiris Pelekis

# Set the working directory
WORKDIR  /app

# Install D-ITG and compile
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y make && \
    apt-get install -y g++ && \
    apt-get install -y unzip && \
    apt-get install -y tcpdump && \
    apt-get install -y iputils-ping &&\
    apt-get install -y procps &&\
    apt-get install -y hping3 &&\
    wget http://traffic.comics.unina.it/software/ITG/codice/D-ITG-2.8.1-r1023-src.zip && \
    unzip D-ITG-2.8.1-r1023-src.zip && \
    mv D-ITG-2.8.1-r1023 D-ITG && \
    rm -r D-ITG-2.8.1-r1023-src.zip

WORKDIR /app/D-ITG/src

RUN make

RUN cp libITG/libITG.so /usr/local/lib

ENV LD_LIBRARY_PATH /usr/local/lib

WORKDIR /app/

COPY ./sender-receiver.sh .

RUN chmod +x sender-receiver.sh

CMD ["./sender-receiver.sh"]
