FROM alpine:latest

MAINTAINER Sotiris Pelekis

# Set the working directory
WORKDIR  /app

# Copy the current directory contents into the container at /app
COPY  ./behaviour-attack-simulator-flask /app/behaviour-attack-simulator-flask/

# Install D-ITG and compile
RUN apk update && \
    apk add wget && \
    apk add make && \
    apk add g++ && \
    apk add unzip && \
    apk add tcpdump && \
    wget http://traffic.comics.unina.it/software/ITG/codice/D-ITG-2.8.1-r1023-src.zip && \
    unzip D-ITG-2.8.1-r1023-src.zip && \
    mv D-ITG-2.8.1-r1023 D-ITG && \
    rm -r D-ITG-2.8.1-r1023-src.zip

WORKDIR /app/D-ITG/src

RUN make

RUN cp libITG/libITG.so /usr/local/lib

ENV LD_LIBRARY_PATH /usr/local/lib

WORKDIR /app/

# install python
RUN apk update && \
    apk add python3 && \
    python3 -m pip install --upgrade pip

WORKDIR /app/behaviour-attack-simulator-flask

RUN pip install -r requirements.txt

#EXPOSE 5000

ENTRYPOINT ["flask"]

CMD ["run", "--host=0.0.0.0"]
