"""empty message

Revision ID: b22da5f84c9d
Revises: 
Create Date: 2020-05-22 20:04:12.654060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22da5f84c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('protocol', sa.Enum('tcp', 'udp', name='protocolenum'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('packet_size_distributions', sa.Enum('constant', 'uniform', 'exponential', 'normal', 'poisson', 'pareto', 'cauchy', 'gamma', 'weibull', name='packetsizedistributionsenum'), nullable=True),
    sa.Column('packet_size_distributions_value_1', sa.Float(), nullable=True),
    sa.Column('packet_size_distributions_value_2', sa.Float(), nullable=True),
    sa.Column('interdeparture_interval_distribution', sa.Enum('constant', 'uniform', 'exponential', 'normal', 'poisson', 'pareto', 'cauchy', 'gamma', 'weibull', name='interdepartureintervaldistributionenum'), nullable=True),
    sa.Column('interdeparture_interval_distribution_value_1', sa.Float(), nullable=True),
    sa.Column('interdeparture_interval_distribution_value_2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FlowToNode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_flow', sa.Integer(), nullable=True),
    sa.Column('fk_node_from', sa.Integer(), nullable=True),
    sa.Column('fk_node_to', sa.Integer(), nullable=True),
    sa.Column('active', sa.Binary(), nullable=True),
    sa.ForeignKeyConstraint(['fk_flow'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['fk_node_from'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['fk_node_to'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FlowToNode')
    op.drop_table('nodes')
    op.drop_table('flows')
    # ### end Alembic commands ###
